name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 11.0.9
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test

  templates:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        template:
          - library-js
          - library-ts
          - cli-js
          - cli-ts
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 11.0.9
      - run: pnpm install
        working-directory: templates/${{ matrix.template }}
      - run: pnpm add -D @types/node@^24.0.0
        working-directory: templates/${{ matrix.template }}
      - run: pnpm lint
        working-directory: templates/${{ matrix.template }}
      - run: pnpm test
        working-directory: templates/${{ matrix.template }}
